// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this files as you wish.
// =================================================================================

package dao

import (
	"suask/internal/dao/internal"
)

// internalAnswersDao is internal type for wrapping internal DAO implements.
type internalAnswersDao = *internal.AnswersDao

// answersDao is the data access object for table answers.
// You can define custom methods on it to extend its functionality as you wish.
type answersDao struct {
	internalAnswersDao
}

var (
	// Answers is globally public accessible object for table answers operations.
	Answers = answersDao{
		internal.NewAnswersDao(),
	}
)

// Fill with you ideas below.
