// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this files as you wish.
// =================================================================================

package dao

import (
	"suask/internal/dao/internal"
)

// internalFavoritesDao is internal type for wrapping internal DAO implements.
type internalFavoritesDao = *internal.FavoritesDao

// favoritesDao is the data access object for table favorites.
// You can define custom methods on it to extend its functionality as you wish.
type favoritesDao struct {
	internalFavoritesDao
}

var (
	// Favorites is globally public accessible object for table favorites operations.
	Favorites = favoritesDao{
		internal.NewFavoritesDao(),
	}
)

// Fill with you ideas below.
