// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this files as you wish.
// =================================================================================

package dao

import (
	"suask/internal/dao/internal"
)

// internalGuestUsersDao is internal type for wrapping internal DAO implements.
type internalGuestUsersDao = *internal.GuestUsersDao

// guestUsersDao is the data access object for table guest_users.
// You can define custom methods on it to extend its functionality as you wish.
type guestUsersDao struct {
	internalGuestUsersDao
}

var (
	// GuestUsers is globally public accessible object for table guest_users operations.
	GuestUsers = guestUsersDao{
		internal.NewGuestUsersDao(),
	}
)

// Fill with you ideas below.
