// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"suask/internal/dao/internal"
)

// internalSettingsDao is internal type for wrapping internal DAO implements.
type internalSettingsDao = *internal.SettingsDao

// settingsDao is the data access object for table settings.
// You can define custom methods on it to extend its functionality as you wish.
type settingsDao struct {
	internalSettingsDao
}

var (
	// Settings is globally public accessible object for table settings operations.
	Settings = settingsDao{
		internal.NewSettingsDao(),
	}
)

// Fill with you ideas below.
