// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this files as you wish.
// =================================================================================

package dao

import (
	"suask/internal/dao/internal"
)

// internalThemesDao is internal type for wrapping internal DAO implements.
type internalThemesDao = *internal.ThemesDao

// themesDao is the data access object for table themes.
// You can define custom methods on it to extend its functionality as you wish.
type themesDao struct {
	internalThemesDao
}

var (
	// Themes is globally public accessible object for table themes operations.
	Themes = themesDao{
		internal.NewThemesDao(),
	}
)

// Fill with you ideas below.
