// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"suask/internal/dao/internal"
)

// internalUpvotesDao is internal type for wrapping internal DAO implements.
type internalUpvotesDao = *internal.UpvotesDao

// upvotesDao is the data access object for table upvotes.
// You can define custom methods on it to extend its functionality as you wish.
type upvotesDao struct {
	internalUpvotesDao
}

var (
	// Upvotes is globally public accessible object for table upvotes operations.
	Upvotes = upvotesDao{
		internal.NewUpvotesDao(),
	}
)

// Fill with you ideas below.
