// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"suask/internal/dao/internal"
)

// viewedDao is the data access object for the table viewed.
// You can define custom methods on it to extend its functionality as needed.
type viewedDao struct {
	*internal.ViewedDao
}

var (
	// Viewed is a globally accessible object for table viewed operations.
	Viewed = viewedDao{internal.NewViewedDao()}
)

// Add your custom methods and functionality below.
