// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this files as you wish.
// =================================================================================

package hello
